;Exercise 1.14:
;
;  Draw the tree illustrating the process generated by the count-change
;  procedure of Section 1.2.2 in making change for 11 cents.
;
;  What are the orders of growth of the space and number of steps used by
;  this process as the amount to be changed increases?
;

;; From section 2.2 we have
;;
;; (define (count-change amount) (cc amount 5))
;; (define (cc amount kinds-of-coins)
;;    (cond ((= amount 0) 1)
;;          ((or (< amount 0) (= kinds-of-coins 0)) 0)
;;          (else (+ (cc amount
;;                       (- kinds-of-coins 1))
;;                   (cc (- amount
;;                          (first-denomination
;;                           kinds-of-coins))
;;                       kinds-of-coins)))))
;; (define (first-denomination kinds-of-coins)
;;    (cond ((= kinds-of-coins 1) 1)
;;          ((= kinds-of-coins 2) 5)
;;          ((= kinds-of-coins 3) 10)
;;          ((= kinds-of-coins 4) 25)
;;          ((= kinds-of-coins 5) 50)))
;;
;; Re-writing in CL yields
(defun first-denomination (kinds-of-coins)
   (cond ((= kinds-of-coins 1) 1)
         ((= kinds-of-coins 2) 5)
         ((= kinds-of-coins 3) 10)
         ((= kinds-of-coins 4) 25)
         ((= kinds-of-coins 5) 50)))

(defun cc (amount kinds-of-coins)
   (cond ((= amount 0) 1)
         ((or (< amount 0) (= kinds-of-coins 0)) 0)
         (T (+ (cc amount
                   (- kinds-of-coins 1))
               (cc (- amount
                      (first-denomination kinds-of-coins))
                   kinds-of-coins)))))

(defun count-change (amount) 
  (cc amount 5))

(count-change 5)
(count-change 11)
(count-change 100)

;; Making change for 11 cents yeilds the following tree
;;
;;                                   (count-change 11)
;;                                          |
;;                                      (cc 11 5)
;;                                          /\_
;;                                         /   \_
;;                                     ___/      \_
;;                                    /            \
;;                               (cc 11 4)      (cc -39 5))
;;                                  _/\_             \_
;;                                _/    \_             \_
;;                               /        \              \
;;                          (cc 11 3)  (cc -14 4)         0
;;                             _/\_          \_
;;                           _/    \_          \_
;;                         _/        \_          \
;;                       _/            \_         0
;;                     _/                \_
;;                   _/                    \____________________________________________
;;                  /                                                                   \
;;              (cc 11 2)                                                             (cc 1 3)
;;                _/\_                                                                   |\___
;;              _/    \__________________________                                        |    \___
;;             /                                 \                                       |        \
;;         (cc 11 1)                          (cc 6 2)                                (c 1 2)   (c -9 3)
;;           _/\_                               _/\__________                            |\___      \___
;;         _/    \_                           _/             \__________                 |    \___      \___
;;        /        \                         /                          \                |        \         \
;;    (cc 11 0)  (cc 10 1)               (cc 6 1)                     (cc 1 2)        (c 1 1)   (c -4 1)     0
;;     _/         __/\                     _/\_                         _/\_             |\___      \___
;;    /        __/    \                  _/    \_                     _/    \_           |    \___      \___
;;   0        /        \                /        \                   /        \          |        \         \
;;        (cc 10 0)  (cc 9 1)       (cc 6 0)  (cc 5 1)           (cc 1 1)  (cc -4 2)  (c 1 0)   (c 0 1)      0
;;        ___/     ____/|          ___/    ______/|               __/\___       \_       |          \__
;;       /        /     |         /       /       |              /       \        \      |             \
;;      0  (cc 9 0)  (cc 8 1)    0  (cc 5 0)  (cc 4 1)      (cc 1 0)  (cc 0 1)     0     0              1
;;        ____/    ____/|          _____/  ______/|             |         |
;;       /        /     |         /       /       |             |         |
;;      0  (cc 8 0)  (cc 7 1)    0  (cc 4 0)  (cc 3 1)          0         1
;;        ____/    ____/|          _____/  ______/|
;;       /        /     |         /       /       |
;;      0  (cc 7 0)  (cc 6 1)    0  (cc 3 0)  (cc 2 1)
;;        ____/    ____/|          _____/  ______/|
;;       /        /     |         /       /       |
;;      0  (cc 6 0)  (cc 5 1)    0  (cc 2 0)  (cc 1 1)
;;        ____/    ____/|          _____/  ______/|
;;       /        /     |         /       /       |
;;      0  (cc 5 0)  (cc 4 1)    0  (cc 1 0)  (cc 1 0)
;;        ____/    ____/|          _____/         |
;;       /        /     |         /               |
;;      0  (cc 4 0)  (cc 3 1)    0                1
;;        ____/    ____/|
;;       /        /     |
;;      0  (cc 3 0)  (cc 2 1)
;;        ____/    ____/|
;;       /        /     |
;;      0  (cc 2 0)  (cc 1 1)
;;        ____/    ____/|
;;       /        /     |
;;      0  (cc 1 0)  (cc 0 1)
;;         ____/        |
;;        /             |
;;       0              1
;;
;; Considering growth in space, the maximum amount of space is the case with
;; pennies, which is equal to the change amount + the number of coins.  Since
;; the parameter to count-change is the amount, we can say count-chage grows
;; in space in O(n), where n is the amount.
;;
;; Resources = O(n)
;;
;; Next we move on to the number of steps.  In this case, we see that there are
;; 55 steps.  Reviewing the structure of the tree as a whole, we can see that
;; this is a tree recursive function, and we should expect that this function
;; will exhibit exponential growth.
;;
;; Upon further review, we can identify some patterns in the tree. First to
;; note is that if the amount is smaller than a given coin size (e.g. 11 cents,
;; and 50 cent coin), that the function discovers that the coin is too large at
;; a cost of two steps.  This pattern can be seen in the upper most part of the
;; tree.  The second pattern we can see is when the function discovers that a
;; coin is valid.  We can see in the right most major branch where the tree
;; discovers that dimes (10 cents) fit in the amount.  Again, the cost is two
;; steps (one for the branch with the coin, and one for the branch without the
;; coin.)  The third pattern we see is the repetition pattern that occurs with
;; pennies.  This can be seen for pennies in the left major branch, and in the
;; center major branch in the tree.  This pattern also costs two steps.
;;
;; We see exponential growth in the tree when you observe that the these
;; patterns repeat as the amount grows.  For example at 4 cents, one branch
;; repeats the pennies pattern.  At  9 cents, we see that pattern repeated
;; in two branches.  At 14 cents, it is repeated in 4 branches.  This 1,2,4
;; pattern is exponential and thus this function demonstrates the exponential
;; growth we expected.
;;
;; Number of Steps = O(n^2)


